name: Monitor and Restart Codespace

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  monitor-codespace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v1
        with:
          version: latest

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: List Codespaces
        id: list-codespaces
        run: gh codespace list --json name,state > codespaces.json

      - name: Check Codespace Status and Restart if Stopped
        run: |
          CODESPACE_NAME=$(jq -r '.[0].name' codespaces.json)
          CODESPACE_STATE=$(jq -r '.[0].state' codespaces.json)
          if [ "$CODESPACE_STATE" == "Stopped" ]; then
            echo "Codespace $CODESPACE_NAME is stopped. Restarting..."
            gh codespace start -c "$CODESPACE_NAME"
          else
            echo "Codespace $CODESPACE_NAME is in state $CODESPACE_STATE. No action needed."
          fi

git add .github/workflows/restart-codespace.yml
git commit -m "Add workflow to monitor and restart Codespace"
git push origin main  # Replace 'main' with your default branch if it's differen
